// Created by Modar Nasser on 13/04/2022.

#pragma once

#include <cstdint>
#include <iostream>

namespace sogl {
    enum class Key {
        Unknown = -1,
        Space,
        Apostrophe,
        Comma,
        Minus,
        Period,
        Slash,
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        Semicolon,
        Equal,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LeftBracket,
        Backslash,
        RightBracket,
        GraveAccent,

        Escape,
        Enter,
        Tab,
        Backspace,
        Insert,
        Delete,
        Right,
        Left,
        Down,
        Up,
        PageUp,
        PageDown,
        Home,
        End,
        CapsLock,
        ScrollLock,
        NumLock,
        PrintScreen,
        Pause,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        F25,
        Numpad0,
        Numpad1,
        Numpad2,
        Numpad3,
        Numpad4,
        Numpad5,
        Numpad6,
        Numpad7,
        Numpad8,
        Numpad9,
        NumpadPoint,
        NumpadDivide,
        NumpadMultiply,
        NumpadSubstract,
        NumpadAdd,
        NumpadEnter,
        NumpadEqual,
        LeftShift,
        LeftControl,
        LeftAlt,
        LeftSuper,
        RightShift,
        RightControl,
        RightAlt,
        RightSuper,
    };

    enum class MouseButton {
        Unknown = -1,
        Left,
        Middle,
        Right,
        Extra1,
        Extra2,
        Extra3,
        Extra4,
        Extra5,
    };

    enum class KeyMod : std::uint8_t {
        Shift       = 0x01,
        Control     = 0x02,
        Alt         = 0x04,
        Super       = 0x08,
        CapsLock    = 0x10,
        NumLock     = 0x20,
    };
    auto operator|(const KeyMod& left, const KeyMod& right) -> KeyMod;
    auto operator|=(KeyMod& left, const KeyMod& right) -> KeyMod;
    auto operator&(const KeyMod& left, const KeyMod& right) -> bool;

    auto operator<<(std::ostream& os, Key key) -> std::ostream&;
    auto operator<<(std::ostream& os, MouseButton btn) -> std::ostream&;
    auto operator<<(std::ostream& os, KeyMod btn) -> std::ostream&;
}
